Repository andela/ah-the-jedi-frontend, pull requests merged in 2019-06, with the labels that each got.

#11 #165305221 Users should be able to Signup
  .babelrc
  .eslintrc
  axiosconfig.js
  jest.config.js
  package.json
  src/assets/styles/emailsent.scss
  src/assets/styles/header.scss
  src/assets/styles/index.scss
  src/assets/styles/signup.scss
  src/assets/styles/variables.scss
  src/components/auth/Signup.js
  src/components/home/Home.js
  src/components/layout/Header.js
  src/components/layout/LoggedOutLinks.js
  src/components/layout/Notfound.js
  src/helpers/index.js
  src/index.html
  src/index.js
  src/redux/actions/ActivateAccountAction.js
  src/redux/actions/SignUpAction.js
  src/redux/constants/index.js
  src/redux/reducers/ActivateAccountReducer.js
  src/redux/reducers/SignUpReducer.js
  src/redux/reducers/index.js
  src/redux/store/index.js
  src/routes/index.js
  src/views/AccountActivateView.js
  src/views/EmailSentView.js
  src/views/SignUpView.js
  tests/AccountActivateReducer.test.js
  tests/AccountActivateView.test.js
  tests/ActivateAccountAction.test.js
  tests/App.test.js
  tests/App.test.jsx
  tests/EmailSentView.test.js
  tests/Header.test.js
  tests/Home.test.js
  tests/Login.test.js
  tests/NotFound.test.js
  tests/SignUpAction.test.js
  tests/SignUpReducer.test.js
  tests/SignUpView.test.js
  tests/Signup.test.js
  webpack.config.js
Labels: Peer Review

#12 #165305223 Users should be able to Login to Authors Haven
  enzyme.config.js
  package.json
  src/assets/images/index.js
  src/assets/styles/index.scss
  src/assets/styles/login.scss
  src/components/App.js
  src/components/auth/Login.js
  src/components/auth/LoginForm.js
  src/components/layout/Header.js
  src/components/layout/LoggedInLinks.js
  src/components/layout/LoggedOutLinks.js
  src/helpers/index.js
  src/index.html
  src/index.js
  src/redux/actions/loginActions.js
  src/redux/constants/index.js
  src/redux/reducers/index.js
  src/redux/reducers/loginReducer.js
  src/redux/store/index.js
  src/routes/index.js
  src/views/LoginView.js
  tests/App.test.jsx
  tests/LoggedInLinks.test.jsx
  tests/Login.test.js
  tests/Login.test.jsx
  tests/LoginActions.test.jsx
Labels: FTL Review

#13 #165305222 Users should be able to reset password.
  .codeclimate.yml
  .eslintrc
  enzyme.config.js
  package.json
  src/assets/styles/ReactToastify.css
  src/assets/styles/login.scss
  src/assets/styles/reset_password.css
  src/components/auth/LoginForm.js
  src/components/auth/PasswordConfirmForm.js
  src/components/auth/ResetPasswordForm.js
  src/components/home/Home.js
  src/components/reset_password.css
  src/components/reset_password.js
  src/helpers/toastify.js
  src/index.html
  src/redux/actions/passwordConfirmAction.js
  src/redux/actions/resetPasswordAction.js
  src/redux/constants/index.js
  src/redux/reducers/index.js
  src/redux/reducers/passwordConfirmReducer.js
  src/redux/reducers/resetPasswordReducer.js
  src/redux/store/index.js
  src/routes/index.js
  src/views/PasswordConfirmView.js
  src/views/ResetPasswordView.js
  tests/password_confirm.test.js
  tests/resetPassword_components.test.js
  tests/reset_password.test.js
Labels: Peer Review

#14 #165305225 Users should be able to view and edit their profiles
  .eslintrc
  package.json
  src/assets/styles/loader.scss
  src/assets/styles/notfound.scss
  src/assets/styles/profile.scss
  src/assets/styles/variables.scss
  src/components/articles/UserArticles.js
  src/components/follows/Follows.js
  src/components/layout/Header.js
  src/components/layout/Loader.js
  src/components/layout/LoggedInLinks.js
  src/components/layout/Notfound.js
  src/components/profiles/Profile.js
  src/helpers/inline.js
  src/index.html
  src/index.js
  src/redux/actions/loginActions.js
  src/redux/actions/profileActions.js
  src/redux/constants/index.js
  src/redux/reducers/index.js
  src/redux/reducers/loginReducer.js
  src/redux/reducers/profileReducer.js
  src/routes/index.js
  tests/Loader.test.js
  tests/Profile.test.js
  tests/ProfileActions.test.js
  tests/ProfileReducers.test.js
  tests/UserArticles.test.js
  tests/UserFollow.test.js
  tests/password_confirm.test.js
  tests/resetPassword_components.test.js
  tests/reset_password.test.js
Labels: Peer Review

#15 #165305224 Implement social login
  .eslintrc
  package.json
  prettier.config.js
  src/assets/styles/social.scss
  src/components/auth/LoginForm.js
  src/components/auth/Signup.js
  src/components/auth/Social.js
  src/index.html
  src/redux/actions/SignUpAction.js
  src/redux/actions/loginActions.js
  src/redux/reducers/SignUpReducer.js
  src/redux/reducers/loginReducer.js
  src/views/SignUpView.js
  tests/Login.test.jsx
  tests/LoginActions.test.jsx
  tests/SignUpAction.test.js
  tests/SignUpView.test.js
  tests/Social.test.js
Labels: Peer Review

#18 #166571933 Fix app responsiveness and social login styling
  src/assets/styles/emailsent.scss
  src/assets/styles/header.scss
  src/assets/styles/login.scss
  src/assets/styles/signup.scss
  src/assets/styles/social.scss
  src/assets/styles/variables.scss
  src/components/auth/Social.js
  src/components/layout/Header.js
  src/components/layout/LoggedInLinks.js
  src/index.html
  tests/Social.test.js
Labels: FTL Review

#16 #166562971 Fix uniform display of error messages throughout the application
  src/assets/styles/common.scss
  src/components/auth/LoginForm.js
  src/components/auth/PasswordConfirmForm.js
  src/components/auth/ResetPasswordForm.js
  src/components/auth/Signup.js
  src/components/profiles/Profile.js
  src/helpers/inputerror.js
  src/redux/actions/loginActions.js
  src/redux/actions/passwordConfirmAction.js
  src/redux/actions/profileActions.js
  src/redux/actions/resetPasswordAction.js
  src/redux/reducers/passwordConfirmReducer.js
  src/redux/reducers/resetPasswordReducer.js
  src/views/LoginView.js
  src/views/PasswordConfirmView.js
  src/views/ResetPasswordView.js
  src/views/SignUpView.js
  tests/Profile.test.js
  tests/ProfileActions.test.js
  tests/SignUpView.test.js
  tests/Signup.test.js
  tests/resetPassword_components.test.js
Labels: Peer Review

#17 #165305237 Users should be able to search and filter articles by tag, title and author.
  __mocks__/fileMock.js
  jest.config.js
  package.json
  src/assets/images/avatar.png
  src/assets/styles/header.scss
  src/assets/styles/searchComponent.scss
  src/assets/styles/variables.scss
  src/components/articles/ArticlesSearch.js
  src/components/articles/AuthorsSearch.js
  src/components/articles/SearchComponent.js
  src/components/articles/SearchEmpty.js
  src/components/articles/TagsSearch.js
  src/components/layout/LoggedInLinks.js
  src/components/layout/LoggedOutLinks.js
  src/redux/actions/SearchAction.js
  src/redux/actions/SignUpAction.js
  src/redux/constants/index.js
  src/redux/reducers/SearchReducer.js
  src/redux/reducers/index.js
  src/redux/store/index.js
  src/routes/index.js
  src/views/SearchView.js
  tests/SearchAction.test.js
  tests/SearchComponents.test.js
  tests/SearchReducer.test.js
  tests/SearchView.test.js
Labels: FTL Review

#20 #166404582 Users should be able to read and delete articles
  package.json
  src/assets/styles/articles.scss
  src/assets/styles/index.scss
  src/assets/styles/loader.scss
  src/assets/styles/variables.scss
  src/components/articles/Article.js
  src/components/articles/OneArticle.js
  src/components/articles/ReadArticle.js
  src/components/articles/UserArticles.js
  src/components/auth/Signup.js
  src/components/home/Home.js
  src/components/reset_password.js
  src/helpers/index.js
  src/helpers/toastify.js
  src/index.html
  src/redux/actions/ActivateAccountAction.js
  src/redux/actions/FetchArticlesActions.js
  src/redux/actions/SignUpAction.js
  src/redux/actions/loginActions.js
  src/redux/constants/index.js
  src/redux/reducers/FetchArticlesReducer.js
  src/redux/reducers/index.js
  src/redux/reducers/loginReducer.js
  src/routes/index.js
  src/views/AccountActivateView.js
  src/views/AllArticles.js
  src/views/EmailSentView.js
  tests/FetchAllArticles.test.js
  tests/FetchArticle.test.js
  tests/FetchDeleteArticlesActions.test.js
  tests/FetchDeleteArticlesReducer.test.js
  tests/UserArticles.test.js
Labels: Peer Review

#24 #165305226 Users create & update article
  enzyme.config.js
  package.json
  src/assets/styles/app.scss
  src/assets/styles/createArticle.scss
  src/assets/styles/notfound.scss
  src/assets/styles/variables.scss
  src/components/App.js
  src/components/articles/CreateArticle.js
  src/components/articles/OneArticle.js
  src/components/layout/Header.js
  src/components/layout/LoggedInLinks.js
  src/components/layout/Notfound.js
  src/helpers/image_uploader.js
  src/helpers/is_empty.js
  src/redux/actions/ActivateAccountAction.js
  src/redux/actions/CreateArticleAction.js
  src/redux/actions/SignUpAction.js
  src/redux/actions/UpdateArticleAction.js
  src/redux/constants/index.js
  src/redux/reducers/CreateArticleReducer.js
  src/redux/reducers/UpdateArticleReducer.js
  src/redux/reducers/index.js
  src/routes/index.js
  src/views/CreateArticleView.js
  src/views/UpdateArticleView.js
  tests/ActivateAccountAction.test.js
  tests/CreateArticle.test.js
  tests/CreateArticleAction.test.js
  tests/CreateArticleReducer.test.js
  tests/CreateArticleView.test.js
  tests/Profile.test.js
  tests/SignUpAction.test.js
  tests/UpdateArticleReducer.test.js
  tests/UpdateArticleView.test.js
  tests/UpdateArticlesAction.test.js
Labels: Peer Review

#19 #165305228 Implement create and read on comments
  package.json
  src/assets/styles/comments.scss
  src/assets/styles/variables.scss
  src/components/articles/OneArticle.js
  src/components/comments/Comments.js
  src/components/comments/createComment.js
  src/components/comments/threadComment.js
  src/components/reset_password.css
  src/redux/actions/CreateCommentAction.js
  src/redux/actions/FetchCommentsAction.js
  src/redux/constants/index.js
  src/redux/reducers/FetchCommentsReducer.js
  src/redux/reducers/FetchOneArticleReducer.js
  src/redux/reducers/createCommentReducer.js
  src/redux/reducers/index.js
  src/routes/index.js
  src/views/CreateCommentView.js
  src/views/CreateThreadedCommentView.js
  tests/CommentReducer.test.js
  tests/CreateComment.test.js
  tests/FetchComments.test.js
  tests/commentActions.test.js
Labels: WIP

#27 #165305232 users should be able to share articles
  src/assets/styles/articles.scss
  src/components/articles/OneArticle.js
  src/components/auth/Signup.js
  src/helpers/socialShare.js
  src/redux/constants/index.js
  tests/SocialShare.test.js
Labels: FTL Review

#26 #166639551 Fix profile and login tests.
  src/components/profiles/Profile.js
  src/helpers/index.js
  src/helpers/inputerror.js
  src/redux/actions/loginActions.js
  tests/Helpers.test.js
  tests/LoggedInLinks.test.jsx
  tests/LoginActions.test.jsx
  tests/Profile.test.js
  tests/ProfileReducers.test.js
Labels: FTL Review, Peer Review

#29 #165305229 Implement pagination support for articles
  src/assets/styles/articles.scss
  src/components/articles/Pagination.js
  src/components/articles/TagsSearch.js
  src/components/comments/Comments.js
  src/redux/actions/FetchArticlesActions.js
  src/redux/constants/index.js
  src/views/AllArticles.js
  tests/FetchDeleteArticlesActions.test.js
  tests/Pagination.test.js
Labels: Approved

#33 #165305239 Bookmark articles for reading later
  src/assets/styles/articles.scss
  src/components/articles/Bookmark.js
  src/components/articles/OneArticle.js
  src/components/articles/ReadArticle.js
  src/redux/actions/CreateCommentAction.js
  src/redux/actions/bookmarkActions.js
  src/redux/constants/index.js
  src/redux/reducers/bookmarkReducer.js
  src/redux/reducers/index.js
  tests/Bookmark.test.js
  tests/BookmarkAction.test.js
  tests/BookmarkReducer.test.js
  tests/commentActions.test.js
Labels: WIP

#30 #165305231 users should be able to add tags and view articles by tags.
  src/assets/styles/articles.scss
  src/assets/styles/searchComponent.scss
  src/components/articles/OneArticle.js
  src/components/articles/ReadArticle.js
  src/components/articles/SearchArticleByTag.js
  src/components/articles/SearchComponent.js
  src/components/articles/SearchTagEmpty.js
  src/components/articles/TagsSearch.js
  src/redux/actions/TagsAction.js
  src/redux/constants/index.js
  src/redux/reducers/TagsReducer.js
  src/redux/reducers/index.js
  src/routes/index.js
  src/views/AllArticles.js
  src/views/SearchView.js
  tests/FetchArticle.test.js
  tests/SearchArticleByTag.test.js
  tests/TagsAction.test.js
  tests/TagsReducer.test.js
  tests/commentActions.test.js
Labels: Peer Review

#32 #166785601 implement Users should be able to report an article
  package.json
  src/assets/styles/articles.scss
  src/assets/styles/variables.scss
  src/components/articles/OneArticle.js
  src/components/articles/ReadArticle.js
  src/components/profiles/Profile.js
  src/components/profiles/UserReports.js
  src/helpers/Modal.js
  src/redux/actions/ArticlesReportsActions.js
  src/redux/constants/index.js
  src/redux/reducers/ CreateReportReducer.js
  src/redux/reducers/FetchOneArticleReducer.js
  src/redux/reducers/index.js
  tests/Modal.test.js
  tests/ReportActions.test.js
  tests/ReportReducers.test.js
  tests/UserReports.test.js
Labels: Approved

#35 #165305230 like and dislike of articles
  src/assets/styles/articles.scss
  src/components/articles/OneArticle.js
  src/components/articles/ReadArticle.js
  src/helpers/image_uploader.js
  src/redux/actions/CreateCommentAction.js
  src/redux/actions/FetchArticlesActions.js
  src/redux/constants/index.js
  src/redux/reducers/FetchArticlesReducer.js
  src/redux/reducers/loginReducer.js
  tests/FetchDeleteArticlesReducer.test.js
  tests/LikeDislikeActions.test.js
Labels: Approved

#36 #165305236 Implement opt in or out of notifications
  src/assets/styles/header.scss
  src/components/layout/Header.js
  src/components/layout/LoggedInLinks.js
  src/redux/actions/CreateCommentAction.js
  src/redux/actions/NotificationsOptinAction.js
  src/redux/constants/index.js
  src/redux/reducers/NotificationsOptInOutReducer.js
  src/redux/reducers/index.js
  src/views/OptInOutView.js
  tests/OptInOutComponent.test.js
  tests/OptInOutNotifyAction.test.js
  tests/OptInOutReducer.test.js
Labels: Peer Review

#31 #165305233 Users should be able to follow each other
  src/assets/styles/follower.scss
  src/assets/styles/profile.scss
  src/components/articles/AuthorsSearch.js
  src/components/follows/FollowButton.js
  src/components/follows/Follower.js
  src/components/follows/FollowersList.js
  src/components/follows/FollowingList.js
  src/components/profiles/Profile.js
  src/helpers/Authhelper.js
  src/redux/actions/followAction.js
  src/redux/actions/followersAction.js
  src/redux/constants/index.js
  src/redux/reducers/followReducer.js
  src/redux/reducers/followersReducer.js
  src/redux/reducers/index.js
  src/redux/store/index.js
  tests/FollowAction.test.js
  tests/FollowButton.test.js
  tests/FollowReducer.test.js
  tests/Follower.test.js
  tests/FollowersActions.test.js
  tests/FollowersList.test.js
  tests/FollowersReducer.test.js
  tests/FollowingList.test.js
  tests/Helpers.test.js
  tests/OptInOutReducer.test.js
  tests/Profile.test.js
  tests/SearchComponents.test.js
  webpack.config.js
Labels: FTL Review
